name: Manually trigger an Azure Machine Learning job

on:
  workflow_dispatch:
    inputs:
      resource_group:
        description: 'Resource group'
        required: true
        default: 'demo-aml-rg'
      workspace_name:
        description: 'Workspace name'
        required: true
        default: 'demo-aml-workspace'  

jobs:
  train:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repo
      uses: actions/checkout@main
    - name: Install az ml extension
      run: az extension add -n ml -y
    - name: Azure login
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS}}
    - name: Trigger Azure Machine Learning job
      run: |
        ls -lrt
        az ml job create --file src/azureml/training/train.yml --web --resource-group ${{ github.event.inputs.resource_group }} --workspace-name ${{ github.event.inputs.workspace_name }}


